[package]
name = "olis_string"
version = "0.1.1"
edition = "2021"
description = "Small-string optimization for Rust, aims to replace std::string::String"
license = "MIT"

[features]
default = ["nightly"]
nightly = []
